theme: jekyll-theme-minimal

title: SiphWeb
description: The effects of predator traits on the structure of oceanic food webs

logo: img/siphweb_white.png
show_downloads: false
google_analytics: UA-120532600-1
